# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14WVe597F-hUaTZm3YP2w3lh21pKHLFLV
"""

import random
import string

def password_generator(length, use_uppercase, use_numbers, use_special_chars):
    """
    Generates a random password of the given length and complexity.

    Args:
        length (int): The length of the password.
        use_uppercase (bool): Whether to include uppercase letters.
        use_numbers (bool): Whether to include numbers.
        use_special_chars (bool): Whether to include special characters.

    Returns:
        str: The generated password.
    """
    chars = string.ascii_lowercase
    if use_uppercase:
        chars += string.ascii_uppercase
    if use_numbers:
        chars += string.digits
    if use_special_chars:
        chars += string.punctuation

    password = ''.join(random.choice(chars) for _ in range(length))
    return password

# Example usage:
length = int(input("Enter password length: "))
use_uppercase = input("Include uppercase letters? (y/n): ").lower() == 'y'
use_numbers = input("Include numbers? (y/n): ").lower() == 'y'
use_special_chars = input("Include special characters? (y/n): ").lower() == 'y'

password = password_generator(length, use_uppercase, use_numbers, use_special_chars)
print("Generated password:", password)